sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Hwb2003108@@.

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: java-web666

  redis:
    host: localhost
    port: 6379
    database: 0

  wechat:
    appid: wx297eaf28a8c3b115
    secret: 93ca65e4bb2617d451bd2279b719d3ba